# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombresc', models.TextField()),
                ('apellidosc', models.TextField()),
                ('emailc', models.TextField()),
                ('clavec', models.TextField()),
                ('estadoc', models.CharField(choices=[(0, 'invalidado'), (1, 'validado')], max_length=10)),
                ('telefonoc', models.TextField()),
                ('direccion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='domiciliarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombresd', models.TextField()),
                ('apellidosd', models.TextField()),
                ('emaild', models.TextField()),
                ('claved', models.TextField()),
                ('estadod', models.CharField(choices=[(0, 'invalidado'), (1, 'validado')], max_length=10)),
                ('telefonod', models.TextField()),
                ('documento', models.TextField()),
                ('reputacion', models.IntegerField()),
                ('rostro', models.FileField(upload_to='')),
            ],
        ),
    ]
