# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domicilios', '0002_auto_20171026_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[(0, 'Moto'), (1, 'Carro'), (2, 'Camión')], max_length=8)),
                ('placa', models.CharField(max_length=7)),
                ('domiciliarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domicilios.domiciliarios')),
            ],
        ),
    ]
